// src/styles.js
const styles = {
    appContainer: {
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'flex-start',
        height: '100vh',
        width: '100%',
        padding: '20px',
        boxSizing: 'border-box',
        backgroundColor: '#f0f0f0',
        fontFamily: 'sans-serif',
    },
    header: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-around',
        marginBottom: '20px',
        backgroundColor: '#fff',
        borderRadius: '8px',
        overflow: 'hidden',
        boxShadow: '0 2px 4px rgba(0, 0, 0, 0.1)',
    },
    navButton: {
        flex: 1,
        padding: '15px 0',
        border: 'none',
        backgroundColor: 'transparent',
        cursor: 'pointer',
        fontSize: '16px',
        color: '#555',
        transition: 'color 0.3s ease, background-color 0.3s ease',
        textAlign: 'center',
    },
    navButtonActive: {
        color: '#007bff',
        borderBottom: '2px solid #007bff',
        fontWeight: 'bold',
    },
    contentSection: {
        flexGrow: 1,
        backgroundColor: '#fff',
        padding: '20px',
        borderRadius: '8px',
        boxShadow: '0 2px 4px rgba(0, 0, 0, 0.1)',
        overflowY: 'auto',
    },
    heading: {
        fontSize: '24px',
        marginTop: 0,
        marginBottom: '20px',
        color: '#333',
        textAlign: 'center',
    },
    ul: {
        listStyle: 'none',
        padding: 0,
        margin: 0,
    },
    listItem: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: '#fff',
        border: '1px solid #eee',
        borderRadius: '5px',
        padding: '15px',
        marginBottom: '10px',
        wordBreak: 'break-word',
    },
    listItemText: {
        flex: 1,
        marginRight: '10px',
        color: '#666',
    },
    listItemHopeText: {
        fontWeight: 'bold',
        color: '#333',
    },
    deleteButton: {
        padding: '8px 12px',
        backgroundColor: '#dc3545',
        color: 'white',
        border: 'none',
        borderRadius: '4px',
        cursor: 'pointer',
        flexShrink: 0,
        marginLeft: '5px',
    },
    completeButton: {
        padding: '8px 12px',
        backgroundColor: '#28a745',
        color: 'white',
        border: 'none',
        borderRadius: '4px',
        cursor: 'pointer',
        flexShrink: 0,
    },
    formParagraph: {
        marginBottom: '15px',
        fontSize: '16px',
        color: '#555',
    },
    formInput: {
        width: 'calc(100% - 100px)',
        padding: '10px',
        border: '1px solid #ccc',
        borderRadius: '4px',
        fontSize: '16px',
        marginLeft: '10px',
    },
    addButton: {
        display: 'block',
        width: '100%',
        padding: '12px',
        backgroundColor: "blue",
        color: 'white',
        border: 'none',
        borderRadius: '4px',
        cursor: 'pointer',
        fontSize: '18px',
        marginTop: '20px',
    },
    footer: {
        marginTop: '20px',
        textAlign: 'center',
        fontSize: '16px',
        color: '#555',
        paddingTop: '10px',
        borderTop: '1px solid #eee',
    }
};

export default styles;
